language: generic
sudo: required
services :
  - docker


before_install:
  - docker build -t wojtasowaty/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true wojtasowaty/docker-react npm run test
